-- (1)
-- CREATE TABLE CUSTOMERS(
-- CID CHAR(8) NOT NULL UNIQUE,
-- CNAME CHAR(20) NOT NULL,
-- CITY CHAR(20) NOT NULL,
-- DISCNT FLOAT NOT NULL,
-- PRIMARY KEY(CID)
-- )

-- CREATE TABLE AGENTS(
-- AID CHAR(8) NOT NULL UNIQUE,
-- ANAME CHAR(20) NOT NULL,
-- CITY CHAR(20) NOT NULL,
-- [PERCENT] INT NULL,
-- PRIMARY KEY(AID),
-- CHECK([PERCENT]<100)
-- )

-- CREATE TABLE PRODUCTS(
-- PID CHAR(8) NOT NULL UNIQUE,
-- PNAME CHAR(20) NOT NULL,
-- PRIMARY KEY(PID)
-- )

-- (2)
-- CREATE TABLE ORDERS(
-- ORDNA CHAR(8) NOT NULL UNIQUE,
-- [MONTH] INT NOT NULL,
-- CID CHAR(8) NOT NULL,
-- AID CHAR(8) NOT NULL,
-- PID CHAR(8) NOT NULL,
-- QTY INT NULL,
-- DOLLARS FLOAT NULL,

-- FOREIGN KEY(CID) REFERENCES CUSTOMERS ON DELETE CASCADE,
-- FOREIGN KEY(AID) REFERENCES AGENTS ON DELETE CASCADE,
-- FOREIGN KEY(PID) REFERENCES PRODUCTS ON DELETE CASCADE,
-- PRIMARY KEY(ORDNA)
-- )


-- (3)
-- ALTER TABLE PRODUCTS ADD CITY CHAR(8), QUANTITY CHAR (8), PRICE CHAR(8)



-- (4)
-- CREATE INDEX IX_CID ON CUSTOMERS(CID)
-- CREATE INDEX IX_AID ON AGENTS(AID)
-- CREATE INDEX IX_PID ON PRODUCTS(PID)
-- CREATE INDEX IX_OR ON ORDERS(ORDNA)


-- (5)
-- DROP INDEX CUSTOMERS.IX_CID
-- DROP INDEX AGENTS.IX_AID
-- DROP INDEX PRODUCTS.IX_PID
-- DROP INDEX ORDERS.IX_OR

-- (6)
-- CREATE UNIQUE INDEX IX_CNAEM ON CUSTOMERS(CNAME DESC)

-- (7)
-- ALTER TABLE AGENTS DROP COLUMN CITY

-- (8)
-- ALTER TABLE CUSTOMERS ALTER COLUMN CITY CHAR(40)

-- (9)
-- DROP TABLE ORDERS
