-- (3.1)
-- SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- BEGIN TRAN
--   SELECT TOP 5 sid FROM students WHERE grade=2000 ORDER BY sid;
--   WAITFOR DELAY '00:00:20';
--   SELECT TOP 5 sid FROM students WHERE grade=2000 ORDER BY sid;
-- COMMIT;

-- (3.2)
INSERT INTO STUDENTS VALUES ('12345987', 'ABC', 'ABC', 2000)
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM STUDENTS WHERE SID='12345987'
IF @@ROWCOUNT<>0
    BEGIN   
        WAITFOR DELAY '00:00:20'
        SELECT * FROM STUDENTS WHERE SID='12345987'
    END
ROLLBACK TRAN

