-- (3.1)
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
INSERT INTO students VALUES ('new_id_xxx','abc','abc@google.com',2000);


-- (3.2)
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
DELETE FROM STUDENTS WHERE SID='12345987'

