-- -- LC 8 skip LC 7(login and profile)

-- (1)
SELECT COUNT(*)
FROM CHOICES, COURSES
WHERE CHOICES.cid=COURSES.cid
AND COURSES.cname='c++'

SELECT COUNT(*)
FROM CHOICES, COURSES
WHERE CHOICES.cid=COURSES.cid
AND COURSES.cname='c++'
AND CHOICES.score>=60

SELECT COUNT(*)
FROM CHOICES, COURSES
WHERE CHOICES.cid=COURSES.cid
AND COURSES.cname='c++'
AND CHOICES.score<60

SELECT COUNT(*)
FROM CHOICES, COURSES
WHERE CHOICES.cid=COURSES.cid
AND COURSES.cname='c++'
AND CHOICES.score IS NULL

-- (2)
SELECT STUDENTS.sid, SCORE
FROM CHOICES, STUDENTS, COURSES
WHERE CHOICES.SID=STUDENTS.sid
AND COURSES.cid=CHOICES.cid
AND COURSES.cname='c++'
ORDER BY score


-- (3)
SELECT DISTINCT SCORE
FROM CHOICES, STUDENTS, COURSES
WHERE CHOICES.sid=STUDENTS.sid
AND COURSES.CID=CHOICES.cid
AND COURSES.cname='c++'
ORDER BY score

-- (4)
SELECT GRADE, COUNT(*) AS COUNT
FROM STUDENTS
GROUP BY grade
ORDER BY COUNT

-- (5)
SELECT CHOICES.cid, CNAME, COUNT(*) AS count, AVG(SCORE) AS avg, SUM(SCORE) AS sum, MAX(SCORE) AS max, MIN(SCORE) AS min
FROM CHOICES, COURSES
WHERE CHOICES.cid=COURSES.cid
GROUP BY CHOICES.cid, COURSES.cname

-- (6)
SELECT DISTINCT GRADE
FROM STUDENTS
WHERE GRADE IS NOT NULL
AND GRADE>=ALL(
    SELECT GRADE
    FROM STUDENTS
    WHERE GRADE IS NOT NULL
)

